name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CONTABO_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.CONTABO_PORT}} -H ${{ secrets.CONTABO_HOST }}  >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -p ${{ secrets.CONTABO_PORT }}" ./dist/ ${{ secrets.CONTABO_USERNAME }}@${{ secrets.CONTABO_HOST }}:/usr/share/nginx/html/node-deployment/

      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USERNAME }}
          key: ${{ secrets.CONTABO_PRIVATE_KEY }}
          port: ${{ secrets.CONTABO_PORT }}
          script: |
            cd /usr/share/nginx/html/node-deployment/
            git fetch origin main
            git reset --hard FETCH_HEAD
            git clean -d -f --exclude secrets
            npm install --production
            chown $(whoami) . # PM2 doesn't recognize root user from Github Actions
            npm start
