name: "Node Integration"
on: 
  pull_requests:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  node-application-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm test
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"