name: SonarQube Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests and generate coverage
        run: |
          npm test -- --coverage
          # Ensure coverage data is generated in coverage/lcov.info

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=shuvo-asl_node-deployment \
            -Dsonar.branch.name=develop \
            -Dsonar.host.url=https://sonarcloud.io  # Change to your SonarQube URL
